
val run_examples : unit -> 'a

val example0 : unit -> unit
val example1h : unit -> unit
val example1v : unit -> unit
val example2 : unit -> unit
val example3 : unit -> unit
val example4 : unit -> unit
val example5 : unit -> unit
val example6 : unit -> unit
val example7 : unit -> unit
val example8 : unit -> unit
val example9 : unit -> unit
val example10 : unit -> unit
val example11 : unit -> unit
val example12 : unit -> unit
val example13 : unit -> unit
val example14 : unit -> unit
val example15 : unit -> unit
val example16 : unit -> unit
val example17 : unit -> unit
val example18 : unit -> unit
val example19 : unit -> unit
val example20 : unit -> unit
val example21 : unit -> unit
val example21bis : unit -> unit
val example21ter : unit -> unit
val example22 : unit -> unit
val example23 : unit -> unit
val example23bis : unit -> unit
val example24 : unit -> unit
val example25 : unit -> unit
val example25bis : unit -> unit
val example26 : unit -> unit
val example26bis : unit -> unit
val example27 : unit -> unit
val example28 : unit -> unit
val example29 : unit -> unit
val example30 : unit -> unit
val example31 : unit -> unit
val example32 : unit -> unit
val example33 : unit -> unit
val example34 : unit -> unit
val example35 : unit -> unit
val example35bis : unit -> unit
val example35ter : unit -> unit
val example36 : unit -> unit
val example37 : unit -> unit
val example38 : unit -> unit
val example39 : unit -> unit
val example39bis : unit -> unit
val example40 : unit -> unit
val example41 : unit -> unit
val example42 : unit -> unit
val example43 : unit -> unit
val example44 : unit -> unit
val example45 : unit -> unit
val example46 : unit -> unit
val example47 : unit -> unit
val example48 : unit -> unit
val example49 : unit -> unit
val example50 : unit -> unit
val example51 : unit -> unit